### ISSUE TITLE
Include recovered video names in the periodic email

### ISSUE THREAD

**Issue by dreasgrech** [ninsky/recovermyvideotracker#10]
Would it be possible to actually include the names of the recovered videos in the "You have 3 recovered YouTube videos" email that is sent?

That way, the names of the videos are never lost since they're forever archived in an email.

I've had an account here since April and had loads of recovered titles yet recently all of them were lost (supposedly due to this database flush?), but if those video names were included in that email, than nothing would have been lost.

Thank you for your time and your service.

**Comment by ninsky** [comment]
Hallo Andreas, please see this answer http://disq.us/p/24gofwm

BR
Nino
