### ISSUE TITLE
Exposed phpinfo() page

### ISSUE THREAD

**Issue by Arinerron** [ninsky/recovermyvideotracker#12]
There is a phpinfo() page at https://www.recovermy.video/test.php which leaks a decent amount of information about your app's environment.

**Comment by Arinerron** [comment]
Thanks for the free service btw, it's a lifesaver.

**Comment by ninsky** [comment]
Wow, will fix it immediately, thanks. I think that's a page created by my hoster. Have to talk to them. How did you find it?

**Comment by ninsky** [comment]
Fixed

**Comment by ninsky** [comment]
Fixed
