### ISSUE TITLE
List/export video titles (including "Liked videos")

### ISSUE THREAD

**Issue by hellpe** [ninsky/recovermyvideotracker#15]
Could it be possible to display and/or download a list of all video titles in any playlist? I understand from [this comment](https://www.recovermy.video/how-to-recover-titles-of-deleted-youtube-videos#comment-4320111312) that the "liked" playlist cannot be tracked for changes, so I'm just looking for a way to retrieve the names of the videos in my playlists at a given time. Currently, RecoverMy.video only displays the number of videos on my playlists without additional info.

**Comment by ninsky** [comment]
Hello Hellpe

I've just rechecked the YouTube docs and I think it should now be possible to track the "liked" and "disliked" videos (but still not the "watched" videos).

Let me put this to my todo list. 

BR
Nino

**Comment by ninsky** [comment]
See https://github.com/ninsky/recovermyvideotracker/issues/11

**Comment by ninsky** [comment]
Hello @hellpe 

What do you think about an export tool like I've [proposed here](https://github.com/ninsky/recovermyvideotracker/issues/32#issuecomment-780148691)? Would be happy to get some user input.

BR
Nino

**Comment by hellpe** [comment]
Hello @ninsky, indeed such a tool would be very useful to me.
My personal usecase for this would be to get the names of songs I've added to my YouTube playlists, in order to remember what was in those playlists after songs get deleted. So, after having created a playlist I'm happy with, I could export it in CSV and have a backup of its contents. Saving the date of addition would be a nice plus, too.

**Comment by ninsky** [comment]
Hello @hellpe 

I've put an export tool to production. You can find it in the main menu. I would be happy to get some feedback if it's useful or something is missing.

BR
Nino
