### ISSUE TITLE
Open source code

### ISSUE THREAD

**Issue by megapro17** [ninsky/recovermyvideotracker#16]
I've seen that you have no interest in this project, ignoring all feature requests, site does not develop, so there only way to help this site alive

**Comment by ninsky** [comment]
Hello megapro17

This site is pretty alive :) I'm very busy to scale this website to guarantee performance. These improvements have to be done before implementing any new features. But you're right in terms that things could develop faster. I have currently no intention to open source RecoverMy.Video.

BR
Nino
