### ISSUE TITLE
deleted videos not listed, only private videos

### ISSUE THREAD

**Issue by ChrisIdema** [ninsky/recovermyvideotracker#19]
I have many playlists with deleted videos( in part because of the recent purge). I want the titles of those videos or at least the automated youtube and archive links. But it only lists videos that have been changed to private.

**Comment by ninsky** [comment]
Hello ChrisIdema,
thanks for your report. This bug [was already reported](https://github.com/ninsky/recovermyvideotracker/issues/17). I'm gonna fix this as soon as possible.

BR
Nino
