### ISSUE TITLE
Show the video id/url on the page 

### ISSUE THREAD

**Issue by JXWw3wLD9LArcR7c** [ninsky/recovermyvideotracker#20]
**Is your feature request related to a problem? Please describe.**
Trying to recover videos with youtubedl sometimes, I get the ids for the videos and I try to see if it's a video I had already downloaded. It is better than using this service because I can filter things out and I have the info on the filename already, but it only works if I had already downloaded the video. If the video is not downloaded, I have to search for it to know what it even was about. If I can't find it, I am doomed. There is no way I can find the titles of the deleted videos on youtubedl, only the ids.

[This is the script I use.](https://pastebin.com/F3ZC3PJW) The videos that show as missing will only show on cmd, not on the output log (deleteme.txt). The log helps me filter out the videos that were downloaded succesfully. (I copy and paste the errors to notepad)

**Describe the solution you'd like**
Currently, I can't use this service and youtubedl at the same time, but I want to. I could do this if the video id's/urls are shown in the page instead of just the hyperlinks. That way it will be possible for me to find both videos I had already downloaded and also videos I haven't downloaded. Currently, it isn't possible for me to find information on videos that I haven't downloaded.

**Describe alternatives you've considered**
I mean, just googling it, I could also look on the site but I would have to scroll down and see. There is no way I can just jump to what I am looking for because all I have is the id, not the title. It would be a very tedious and hard process.

**Additional context**
[Mouse](https://youtu.be/7PsYBcrLBVk)
![image](https://user-images.githubusercontent.com/41213690/88246288-0d4c7100-cc68-11ea-8f59-c39debcf0b5d.png)

**Comment by ninsky** [comment]
Hi Simon

From a UX perspective it would be not a useful addition to show the whole URL/ID in the listing of recovered video titles. It would clutter the listing and it would be less readable/scannable.

_**It is better than using this service because I can filter things out**_  
What do you mean with "filter things out"? Is your idea related to this [feature request](https://github.com/ninsky/recovermyvideotracker/issues/8)?

BR
Nino

**Comment by JXWw3wLD9LArcR7c** [comment]
Maybe show the ID only? The ID is pretty small, it looks something like this: pQYd5T3hRK0

By filtering things out, I mean that it allows me to find only videos that had been deleted on one of my playlists (instead of all of them). This is useful because I have those videos downloaded

**Comment by ninsky** [comment]
Okay, your filtering issue is already addressed within in this tracker. I'm sorry to say that I won't show the videoID as it's already there in form of a link, which is the better solution for 99,9% of the users.
