### ISSUE TITLE
Broken email verification

### ISSUE THREAD

**Issue by donny-max** [ninsky/recovermyvideotracker#21]
When I try to click the link in the verification email sent, this happens

[Image](https://photos.app.goo.gl/4YNCgNiCY4SS6Mzi6)

**Comment by ninsky** [comment]
Hello donny-max

Thanks for your message. I've encountered such an issue from another user. In the other user's case the user requested multiple email confirmation emails as the first email wasn't delivered immediately after registration. At the moment the first email was delivered, the token within the first email was invalid as there was already a second email on its way with a new token.

If you could send me the email confirmation email (or link within the email) and your email address to me, I would be happy to investigate about this. You can find [my contact here](https://www.recovermy.video/imprint).

Thanks in advance
Nino

**Comment by ninsky** [comment]
Hello donny-max

This should be fixed by now.

BR
Nino
