### ISSUE TITLE
Cross-reference info to recover previous videos

### ISSUE THREAD

**Issue by eocejo** [ninsky/recovermyvideotracker#24]
Would it be possible to leverage the information from other users to try to recover videos lost before signing up for the service?
Having that feature could greatly increase the usefulness of the service.

Thank you!

**Comment by ninsky** [comment]
Hello eocejo, I'm closing this feature request as it was already discussed [in this issue](https://github.com/ninsky/recovermyvideotracker/issues/2). Thanks anyway for posting!
