### ISSUE TITLE
I’d like to suggest that the Download List function includes links

### ISSUE THREAD

**Issue by Seff27** [ninsky/recovermyvideotracker#26]
At the moment, Download List is a very important feature due to how people need to do it before their account gets deleted. 

However, it only includes titles currently, and not the video links- without the link, there’s no way to figure out what a video was if it only registers as Deleted Video or has a very vague title. You can google a link, but you can’t google “Deleted Video” and have it show up, or a generic title like, for instance, “We Are”.

So yeah, I think Download List would be way better if it included the links.

**Comment by ninsky** [comment]
Hello Steff27

I think in case a video shows up as "deleted video" a link wouldn't help that much as there would be no page on YouTube with further information about this video. As I understand the benefit would be to google the link?

I won't be able to implement this feature request before November 24th. Hopefully we don't need links in future because all deleted video will be revovered. This would also not blow up the list which you can download.

I hope it's okay to close this issue for now. 

Thanks for your suggestion!
Nino

**Comment by Seff27** [comment]
I’m not sure I really understand what you mean by blowing up the download list, you could just have it in another column next to the videos- and even if you can’t implement it before the accounts are deleted, it could still be important at some later date, for the same reason you have an option to google the links straight from the normal list. It’d make sense for the downloaded list to have the same stuff as the normal list, right?

And even if there’s no page on YouTube, a link is still very useful! Like you said, the benefit is to google the list. For instance, just now, by googling the link to some music on my list of deleted videos, I was able to find another page that mentioned it, the artist’s SoundCloud, where they included a link to the YouTube video in the description! So even if a link doesn’t still lead to the video on YouTube, you can still use it to find the video in some cases. Or even just figure out the context and find the creator of the video, which is also useful in some cases.

Btw, I was still able to “download” the links, so to speak, by copy pasting them individually from every single video on the list and bookmarking them in their own bookmark folder. But simply having the links next to the videos in the List Download would be much more convenient.

**Comment by ninsky** [comment]
Hello Steff

Now I can see your point, thanks. I've reopened the issue and put the "enhancement" label on it. So it's ony my todo list.

BR
Nino

**Comment by ninsky** [comment]
Hi @Seff27 

What do you think about an export tool like I've [proposed here](https://github.com/ninsky/recovermyvideotracker/issues/32#issuecomment-780148691)? Would be happy to get some opinions about that.

BR
Nino

**Comment by ninsky** [comment]
Hello @Seff27 

I've put an export tool to production. You can find it in the main menu. I would be happy to get some feedback if it's useful or something is missing. Links are included.

BR
Nino

**Comment by Seff27** [comment]
Wow, that export tool looks amazing! Tysm for adding it! Sorry for not
getting back to you before, I started to write a reply then got distracted,
then this got buried under a bunch of other emails.
