### ISSUE TITLE
Is there a way to recover playlists from my banned account?

### ISSUE THREAD

**Issue by ChrisIdema** [ninsky/recovermyvideotracker#27]
YouTube banned my 8 year old account last week without giving any warning or example (except referring to "harassment").

I can no longer log into YouTube. If I log into recovermy.video. I get the error: 

```
RecoverMy.Video is temporarily not available

This service will work again in 16 hours.

Please come back later.
```

I have logged into recovermy.video last time about a month ago.
Can I recover my playlists?

**Comment by ninsky** [comment]
Hmm, I think it will not be possible. Just try it tomorrow. BR

Chris Idema <notifications@github.com> schrieb am Fr., 20. Nov. 2020, 17:36:

**Comment by ChrisIdema** [comment]
I tried it several times. It doesn't work. I'm done with YouTube now.

**Comment by ninsky** [comment]
Okay, your recovermy.video account will get deleted anyway. If you want to
register a new one, just register after November 24th cet

Chris Idema <notifications@github.com> schrieb am So., 22. Nov. 2020, 10:13:

**Comment by ChrisIdema** [comment]
So there is no way to recover all my playlists? What a bummer. Can't you send me a csv-file with my playlists?

**Comment by ninsky** [comment]
I'm sorry to say that there's no way as all accounts got deleted.
