### ISSUE TITLE
Playlist Manager: Search for videos in Playlists, find duplicates, save original video titles

### ISSUE THREAD

**Issue by Kreavita** [ninsky/recovermyvideotracker#31]
**Is your feature request related to a problem? Please describe.**
Problem: Because I have over 1000 videos on 10+ playlists, I don't remember for every song whether i added the it to a certain playlist or not, and maybe I stumble upon the song from a different uploader some other day and add it to the playlist, or add it to a different playlist which also matches the song. So yeah, its a pain to keep it organized. 😄 

**Describe the solution you'd like**
Enhancing the playlist manager with a list of entries per playlist, a search function through all playlists and an indication if the video is unavailable and in case, its original title. (maybe even a duplicate finder, links to the video/playlist or alternatively a link to a youtube search if the video is taken down)

**Describe alternatives you've considered**
Well, creating my own app to keep track of the Playlists i guess.😉 😂

I believe this request goes a little beyond the original goal of the webpage, but it would be nice to have it all in one place - Nevertheless, thanks for creating it! 😃

**Comment by ninsky** [comment]
Hello Kreavita

I think you've already mentioned it. This would be some kind of "organizer" feature. Definitely useful, but not in scope of this project. In case I run out of tasks I will get back to you but I think that won't happen.

BR
Nino
