### ISSUE TITLE
Download video titles from a playlist

### ISSUE THREAD

**Issue by Lucky9114** [ninsky/recovermyvideotracker#32]
My playlist was deleted by youtube I would really like to recover the titles of the playlist so it can be rebuilt again. Currently I can see the number of videos in the playlist but cannot download or view it.  There seems to be another post about this so I hope that it is possible soon.

**Comment by ninsky** [comment]
Hello Supev

When a whole playlist gets deleted, the playlist also gets deleted on RecoverMy.Video. There's no possibility to distinguish if a playlist got deleted by YouTube or by yourself.

But a feature to download the titles of all playlist videos is maybe a good idea to keep track in case of such a situation. Let's keep this on the backlog/tracker.

BR
Nino

**Comment by ninsky** [comment]
Hello Supev

I'm just thinking about an export tool to give users the possibility to download their YouTube data as a CSV export. Would a export tool like on this draft be useful? What would you change or add?

![image](https://user-images.githubusercontent.com/1623045/108127523-a2eb9a00-70ab-11eb-9633-e4b73173456f.png)

BR
Nino

**Comment by ninsky** [comment]
Hello 

I've put a CSV export tool to production. Therefore I close this issue. I would be happy to get some feedback about the export possibilities.

BR
Nino
