### ISSUE TITLE
Ignore videos that I remove

### ISSUE THREAD

**Issue by hashimaziz1** [ninsky/recovermyvideotracker#35]
Firstly, thanks for being the best solution that I've ever come across to this very annoying YouTube issue. 

Currently the tool tracks all videos in all playlists. This isn't ideal for someone like me who uses temporary playlists where I store things until I have time to listen to them, similar to Watch Later. For example I have a playlist called New Music where I move music that I want to listen to later. When I'm done listening to the music, I remove it from New Music and if I like it, move it to one of my "permanent" playlists. 

Currently the tool considers every time I remove a video from New Music (or any other playlist) as lost. 

One solution would be either to have the ability to exclude playlists from being monitored, but a true fix for this problem would be to ignore (or have an option to ignore) all videos that a user removes from their own playlists, only considering those that actually go offline (deleted or made private) as lost. This to me seems like a much more superior solution rather than keeping track of all updates to playlists, which becomes very noisy when you actively add and remove videos from playlists like I do.

**Comment by ninsky** [comment]
Hello Kaos-Industries

I'm currently working on [this issue](https://github.com/ninsky/recovermyvideotracker/issues/6) which will make it possible to exclude playlists from monitoring. Hopefully I'll be done with it at the end of this week. Let's see how it goes...

It's not possible to distinguish a video removal by you or YouTube. I hope the playlist exclusion will help. As there's already a ticket in place i will close this one. Hope you're fine with that.

BR
Nino
