### ISSUE TITLE
Not Reload the Page when Archiving a Video

### ISSUE THREAD

**Issue by DipstickPinez** [ninsky/recovermyvideotracker#38]
**Is your feature request related to a problem? Please describe.**
Although this is rather minor, it's a little/slow annoying to have the page reload and reset if you archive a video. Is it possible to have it similar to Youtube or similar systems where the video gets removed but your space on the page is kept/the page stays loaded?

**Comment by ninsky** [comment]
Hi
I'm currently working on the page to get loaded faster. I've already did an optimization to get the page loaded faster after logging in. I will also have a look at the archive performance soon. Your Youtube like behaviour would need a bigger effort. Let's try to improve performance with the existing page reload.

I'm closing this for now.

BR
Nino
