### ISSUE TITLE
Website "recovers" removed songs from YouTube Music playlists.

### ISSUE THREAD

**Issue by redJuli21** [ninsky/recovermyvideotracker#39]
**Describe the bug**
Removing songs from YouTube Music playlists count as videos getting "recovered"

**To Reproduce**
1. Make a playlist in YT Music
2. Website monitors it
3. Add a song
4. Remove the song
5. See it getting "recovered"

**Expected behavior**
To not appear "recovered"

**Smartphone (please complete the following information):**
 - Device: Galaxy Note 10 Lite
 - OS: Android 10
 - Browser: Chrome
 - Version: 87

**Additional context**
A solution would be an option to mark playlists as YouTube Music playlists.

**Comment by ninsky** [comment]
Hello @TotallyNotInUse 

Yes, I'm aware of this behaviour. I've already posted an anwer [here](https://github.com/ninsky/recovermyvideotracker/issues/35) about a similar question / feature request.

Meanwhile I think I've found a solution. But I this will take some time to investigate as it will impact my YouTube quota budget. I leave this issue open.

BR
Nino

**Comment by ninsky** [comment]
Hello @TotallyNotInUse 

This is fixed! I'm happy to hear if it works.

BR
Nino
