### ISSUE TITLE
Are you considering open-sourcing (allowing self-hosting)?

### ISSUE THREAD

**Issue by TheTyrius** [ninsky/recovermyvideotracker#4]
**Is your feature request related to a problem? Please describe.**
I love your service, because I hate loosing parts of my playlists.

**Describe the solution you'd like**
OpenSource-ing would allow collaboration (e.g. when API updates break something). Also it would be possible to selfhost, which I consider a plus because in the event of your server shutting down I can spin up my own :)

(Also on a sidenote: I'm not sure: Are you using data collected from other peoples playlists to recover videos of "first-time-users"? That would be a benefit of a centralized instance, but again, should your service ever disappear, others would be able to pick up)

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by ninsky** [comment]
Hi TheTyrius

I don't have any plans to shut it down as I'm a power user by myself and it doesn't make a big difference to operate this service.

But I would be happy to find a way to get my monthly costs covered (cloud hosting, mail service provider). I'm thinking about to try patreon.com or opencollective.com. So users who would be willing to give something back would have a convenient way to do so.   

If I would come to the conclusion to shut it down one day, I would definitely think about to open source the code. But as said: I don't have any plans to stop this service.

BR
Nino

**Comment by TheTyrius** [comment]
Hi, 
that's nice to read. Thanks for considering.

I hope you have a great day :)

**Comment by ninsky** [comment]
Closed
