### ISSUE TITLE
wrong last login date causes wrong amount of lost videos in email

### ISSUE THREAD

**Issue by Aevus-Eye** [ninsky/recovermyvideotracker#41]
i have logged into my account many times. last login today: 7. mar. 2021. the weekly email tells me i was last logged in 13. Feb. 2021 and it tells me that i have 11 newly recovered videos, but i have already archived those. on the website it tells me i have last logged in 30. jan. 2021. 

so your website and email somehow have 2 seperate wrong last logged in dates and sends me emails about lost videos i have already archived. 

i use windows 10 + firefox with extra privacy addons to access your website.

**Comment by ninsky** [comment]
Hello dontknow3d

Thanks for your report! I will investigate this issue as soon as possible and will update this github issue as soon as it's confirmed / fixed.

Thanks for letting me know!

BR
Nino

**Comment by ninsky** [comment]
Hello dontknow3d

Could you send me your registerede email address or YouTube channel link? Just want to be sure that the email didn't get sent to you before you've logged in on 7. mar. 2021.

BR
Nino

**Comment by Aevus-Eye** [comment]
youtube channel: https://youtube.com/channel/UCdKlpcRquRrW4R1w5syn-sA

**Comment by ninsky** [comment]
Thanks dontknow3d, I've fixed this issue today.

BR
Nino
