### ISSUE TITLE
An idea for videos that have been removed from a playlist, but not deleted.

### ISSUE THREAD

**Issue by Aevus-Eye** [ninsky/recovermyvideotracker#42]
**This feature request is related to the problem, that videos that have been removed from playlists also show up here, not just strictly deleted videos.**

**A little note would be good**
a quick little thing that would help newer users would be to just add a little note at the top of the recovery tab, that states that videos that were removed from a playlist also show up here, not just deleted videos. I was very confused, when it happened to me for the first time.

**An actual solution**
But I also have an idea for a solution to the problem, that does not impact your youtube API limit.
Instead of you (the server) checkin if a video still exists, make the client do that. So, whenever the client opens their recovery tab, it tries to load all of the videos there. if it fails to load a video, then the video is probably deleted. but if it could load the video, then it was only removed from the playlist. then you could have a button in the recovery tab that removes all of the videos that could be loaded. 
This way you still get an email if videos were removed from a playlist, but its easy to see which were only removed and which got deleted.

**Comment by ninsky** [comment]
Hello dontknow3d

Basically, this is a very smart idea which would even not harm my IP address for crawling YouTube. In the first place I will recalculate my API limit to do this check via API which would be the fastest and most convenient solution for uses. If this would consume too much API credits, I would fall back to your solution. It will leave this issue open to track this feature request.

Thanks for this great idea!

BR
Nino

**Comment by ninsky** [comment]
Hello dontknow3d

I've implemented an optimization: videos which are manually removed by a user from its playlist should not be considered as recovered any more.

I'm happy to get some feedback if you can confirm that it works. I'm closing this issue for now.

BR
Nino
