### ISSUE TITLE
R

### ISSUE THREAD

**Issue by millmikhalea4** [ninsky/recovermyvideotracker#44]
*Hi my name is mikhalea and I have a question do you know any app or website I can use to view name and information of youtube videos that are private and deleted I know your website can do that but you can't show the name of every  private or deleted youtube videos and I really need a app or website that can show can the name or information of any youtube video that are private or deleted

**Comment by ninsky** [comment]
Hello millmikhalea4

This issue tracker is about bugs and improvements related to RecoverMy.Video. I propose to go to a forum like Reddit.com to post your question there.

BR
Nino

**Comment by millmikhalea4** [comment]
Thank you so much for your help and can you me a link to whare I am
supposed to go once again thank you so much
