### ISSUE TITLE
It didn't detect a removed vidéo in my account

### ISSUE THREAD

**Issue by Navis-Raven** [ninsky/recovermyvideotracker#45]
Nothing detected here:

![image](https://user-images.githubusercontent.com/15887222/115991887-ee01bc00-a5ca-11eb-8c9e-dd881b020983.png)

While a "censored" video is on this playlist: 
![image](https://user-images.githubusercontent.com/15887222/115991912-1e495a80-a5cb-11eb-9e49-c7c9a3dc365f.png)

**Comment by ninsky** [comment]
Hello @Navis-Raven 

So the recovered video "Morad El Hattab..." is not the one which is "non disponible a ete masquee"? There are other reasons this could happen:

- The video was already deleted before your signup on recovermy.video (see "Lost" tab)
- The video was put on your playlist and deleted on YouTube between 2 update cycles (1 week)

Could on of this reasons be an explanation?

BR
Nino

**Comment by Navis-Raven** [comment]
Non this is not "Morad El Hattab..."

"The video was already deleted before your signup", No the video was deleted recently
"The video was put on your playlist and deleted on YouTube between 2 update cycles (1 week)" That's may be more plausible, the video was deleted about 3 or 4 days after it has been uploaded to youtube.

**Comment by ninsky** [comment]
@Navis-Raven yes, if the video was uploaded and deleted before it got synced to RecoverMy.Video, the title can't be recovered. But such videos will be added to yout "Lost" section so you could ask Google/Archive.org.... but it's a matter of luck if such a video got crawled by Google/Archive.org either.

I'm closing this issue as it doesn't seem to be a bug. Hope you're fine with that.

**Comment by Navis-Raven** [comment]
It is not either in Lost section, I've just verified

**Comment by ninsky** [comment]
It would be in Lost section if it would have been a video which was set to private. In your case it's a deleted video. These videos don't get listed under Lost section,

**Comment by Navis-Raven** [comment]
So it is not a nromal behavior, all deleted video should be listed in Lost section. I think you should open a new issue about what you described.

**Comment by ninsky** [comment]
The YouTube API doesn't always deliver all deleted videos (in contrast to private videos)... I think this is some kind of an inconsistence of YouTube. I've encountered this many times and it even changed in the past. As the video was most probably added to your playlist and deleted (by YouTube or the uploader of the video) between 2 update cycles, RecoverMy.Video has never got in touch with it.

**Comment by Navis-Raven** [comment]
It was deleted by Youtube due to actual censorship about COVID.

**Comment by Navis-Raven** [comment]
Maybe if you increase the frequency cycles to 1 time a day, it might solve the problem.

**Comment by ninsky** [comment]
Yes, this would reduce the risk to miss a deleted video. As my YouTube crawling budget is limited I have to stick to a week currently. I will increase frequencey whenever possible.

**Comment by Navis-Raven** [comment]
OK
