### ISSUE TITLE
video not appear in Recovered or Lost

### ISSUE THREAD

**Issue by BruhMomento0** [ninsky/recovermyvideotracker#47]
It did send email that it recoved 1 video and i know exactly what video is gone (i was set to private) but it doest appear in Recovered or Lost
![image](https://user-images.githubusercontent.com/66198490/120089248-aec30f80-c122-11eb-86e6-ddc6ee2268c1.png)
the video was in playlist like 6+ months ,It just got privated 2 days ago
![image](https://user-images.githubusercontent.com/66198490/120089151-c64dc880-c121-11eb-99bf-6bded1f668d2.png)
![image](https://user-images.githubusercontent.com/66198490/120089198-30ff0400-c122-11eb-8aac-79a7ea54658b.png)
the song title is :ここから、ここから(cover)【花寄女子寮】
link: https://www.youtube.com/watch?v=vHMV44Uza4g
all in Recovered and Lost dont have the same link
seem like some song doesnt get recover too (i think)

**Comment by ninsky** [comment]
Hello @BruhMomento0 

I've just checked your database. As you maybe know your YouTube playlists gets synced to RecoverMy.Video about once a week. Your last sync was on "2021-05-23 18:31:24". I can also find your video which you have twice on your database but on different playlists (fav Songs, fav Kano).

The reason why this video wasn't recovered yet is, that it will be recovered on the next sync which should be today or tomorrow. The email you've got must be related to another video.

Please let me know in case the videos didn't get recovered within the next 1-2 days. I will close this ticket within the next days in case everything works fine.

BR
Nino

Note to myseld: videoIds: 4048860, 4048588

**Comment by BruhMomento0** [comment]
It showed up in recoved now.

It didnt write at home page or anywhere that it will showup once a week so that why I thought it was a bug.
![image](https://user-images.githubusercontent.com/66198490/120415380-a4548000-c385-11eb-93bf-02eaf682b009.png)
also there is no FAQ page, I think make a FAQ page is a great idea.

**Comment by ninsky** [comment]
Good catch, @BruhMomento0 !

I've just updated this sentence on the blog article. Will push it to production with my next release. Yes, a FAQ is on my backlog with a high priority. 

Thanks for helping out
Nino
