### ISSUE TITLE
R

### ISSUE THREAD

**Issue by millmikhalea4** [ninsky/recovermyvideotracker#49]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Hi my name is mikhalea and I have a question do you know any app or website I can use to download private and deleted YouTube videos

**Comment by ninsky** [comment]
@millmikhalea4 , how many new issues do you intend to open asking the same question over and over again? I'm not a service point to answer all your unrelated questions. Please just open an issue if you have a problem with RecoverMy.Video. For anything else please use Google. Thank you.

See
https://github.com/ninsky/recovermyvideotracker/issues/44
https://github.com/ninsky/recovermyvideotracker/issues/46
https://github.com/ninsky/recovermyvideotracker/issues/48
http://disq.us/p/2gnpccs
http://disq.us/p/2ghz7h5

**Comment by millmikhalea4** [comment]
I understand I just wanted to know if you could use your website to view
thumbnail and title of youtube videos that are private and deleted if you
also say no I will understand thank you so much for replying to my email
and if I have any more questions I will let you know thank you again and
have a great week
