### ISSUE TITLE
Sign in with Google only shows up sometimes

### ISSUE THREAD

**Issue by xetch2950** [ninsky/recovermyvideotracker#50]
Should you accidentally click x on the sign-in with google you cannot get it to reappear again even by reloading the page.

**Comment by ninsky** [comment]
Hello @xetch2950 

Depending on how many times you've closed the google sign in windows it will show up again according to these hours:
https://developers.google.com/identity/gsi/web/guides/features#exponential_cooldown

BR
Nino
