### ISSUE TITLE
List videos marked as blocked in country

### ISSUE THREAD

**Issue by ayunami2000** [ninsky/recovermyvideotracker#53]
**Is your feature request related to a problem? Please describe.**
Videos that are marked as blocked in country should show up. (E.g. videos taken down by Nintendo are marked as blocked in my country)

**Describe the solution you'd like**
Have it list videos marked as blocked in my country (or any country). The chances to find a video blocked in specific countries is very rare I would think.

**Describe alternatives you've considered**
Using a user script made by a friend that archives details of YouTube videos.

**Additional context**
"[Video blocked in country] video title"

**Comment by ninsky** [comment]
Hello @ayunami2000 

I'm sorry to say that it's not possible to recognize videos which are blocked in your country, You could try to search for such a video in the CSV export of your videos. Maybe it's a normal public video when downloaded by RecoverMy.Video. 

BR
Nino

**Comment by ayunami2000** [comment]
I was thinking if it's blocked in one country then it should be listed as
blocked in a country. So then the user can go check if it is blocked in
their country and if so try to revive the video. It should be possible,
just not to check every country.
