### ISSUE TITLE
Some videos are deleted or no longer available but recovermy.video hasn't tracked them as unavailable

### ISSUE THREAD

**Issue by AuraofMana** [ninsky/recovermyvideotracker#54]
**Describe the bug**
I've had a few videos disappear from my playlists. I know because 1) I see the warning on each playlist saying "some videos are no longer available because YouTube deleted them" and 2) because I use Rythm to play them on Discord, I've had to change my playlists to cap them at 500 songs and some playlists have dropped from 500, yet recovermy.video doesn't think I've lost anything.

**To Reproduce**
N/A

**Expected behavior**
I'd expect a warning as before.

**Screenshots**
N/A

**Additional context**
I know this is going to be hard to prove. Sorry that I can't provide more information. I am assuming recovermy.video works by hashing each playlists and then recheck it every time it needs to sync? So if something is out of place, it would try to see what is missing? I am wondering why it's no longer doing this. Did YouTube change something?

**Comment by ninsky** [comment]
Hello @AuraofMana 

I think the reason could be that the video was added and removed during two update cycles. Please have a look at this discussion over here: https://github.com/ninsky/recovermyvideotracker/issues/45#issuecomment-826903107

The fix would be to have more update cycles. Currently it's about every 7-9 days which is pretty long. Going to reduce this as far as possible.

BR
Nino

**Comment by AuraofMana** [comment]
Thanks for the quick reply @ninsky. I don't see them in my lost section though?

**Comment by ninsky** [comment]
You propably won't see them because I suppose they were never fetched by RecoverMy.Video due to the gap between two syncs
