### ISSUE TITLE
Export Tool has changed. Intentional?

### ISSUE THREAD

**Issue by frjoethesecond** [ninsky/recovermyvideotracker#55]
The Export Tool is no longer allowing the export of all playlist data. It only allows the export of recovered and lost videos.

![Capture](https://user-images.githubusercontent.com/89853774/131516259-2a9458ea-2663-41d4-9d82-0e3ebd90ede1.PNG)

**Comment by ninsky** [comment]
I had to remove it as there where some users with very large data sets which consumed all of the servers RAM to export the data,

**Comment by frjoethesecond** [comment]
> 
> 
> I had to remove it as there where some users with very large data sets which consumed all of the servers RAM to export the data,

That's a shame. I hope you can upgrade the server at some point and restore the feature. Perhaps donations can help with that?

**Comment by ChrisIdema** [comment]
> 
> 
> I had to remove it as there where some users with very large data sets which consumed all of the servers RAM to export the data,

It should be possible to have workarounds for this. Maybe you can add a button "request export" and then you can export it after a certain time (a few days?) to limit server load.
