### ISSUE TITLE
Ability to choose which playlists should be tracked

### ISSUE THREAD

**Issue by mcpjb** [ninsky/recovermyvideotracker#6]
Hey Nino

I was wondering if you could add an option where you could decide which playlists should be tracked. I personally am only really interested in preserving my music playlists, so I don't need those other playlists updated every time I want to find which song I lost. I would find it a shame though to just delete those other playlists just to get faster to my database.

Thus a list of the playlists with a toggle would be pretty handy
I would add the option on this page:

![image](https://user-images.githubusercontent.com/43176014/63963069-79444a80-ca94-11e9-8a70-d316a7990217.png)

all the playlists could be listed under what's currently on the page, with a checkbox next to each of the playlists.

extra afterthought:
In my case I wouldn't have a problem if the option just removed the entire playlists out of the database, though I could imagine that some people would like to keep their playlist in the database, but just not have it updated every time they try to check it.
So if that would be a possibility, then it might be worth it to make it into separate options.

**Comment by ninsky** [comment]
Hello mcpjb

That would be great addition as this would also save some "crawling time". For now, I have some more "high priority" features on my backlog but will also track this with medium priority.

Thanks for your suggestion!
Nino

**Comment by AssassinIronMan** [comment]
I would also appreciate this enhancement to be added.  I have gone over the 8000 video limit mark and now it doesn’t track my videos.  This makes me sad :(

**Comment by ninsky** [comment]
Yes, this would be a good feature but will take some effort. Have to do other things before. I'm sorry to say, that this feature has to wait...

**Comment by ignatremizov** [comment]
Bumping this issue! I can't use the service at all because of this. And it's already been around a year since this issue was made! I think it should have a higher priority. What are some tasks in this project that are more important than this?

**Comment by ninsky** [comment]
Hello guys

Just to give a short update: still working on a major update of RecoverMy.Video. This update will bump the limit from 8k monitored videos to 20k. Another advantage will be that the possibility for a manual update will be removed as the automatic update cycle will get more frequent. Anyway, this feature still makes sense and I will leave it open till it's done.

BR
Nino

**Comment by AssassinIronMan** [comment]
Yay!  Hopefully I’ll be able to use it again ░ ∗ ◕ ں ◕ ∗ ░

**Comment by ignatremizov** [comment]
oof, I have _just_ over the new 20k limit!
<img width="781" alt="Screen Shot 2020-09-07 at 4 27 16 PM" src="https://user-images.githubusercontent.com/8076691/92392519-11085a00-f127-11ea-80e6-8c0d186a16fe.png">

I'll keep track of any future changes though, hope I get to use this cool tool soon!

**Comment by ninsky** [comment]
Hello @ignat980 , @ignat980 , @AssassinIronMan 

Now it's possible to choose which playlists will be tracked. There's a little switch per playlist.

BR
Nino

**Comment by Kaos-Industries** [comment]
> 
> 
> Hello @ignat980 , @ignat980 , @AssassinIronMan
> 
> Now it's possible to choose which playlists will be tracked. There's a little switch per playlist.
> 
> BR
> Nino

Hi Nino, came back looking for this, thank you. Is it currently only possible to do this on initial connection of the channel? I didn't notice any other way to do that, and it would be useful to be able to control when to do this without having to disconnect the channel and lose tracked videos. Thank you once again for your work on this tool.

**Comment by hashimaziz1** [comment]
I came back looking for this feature, and initially posted a comment wondering where this was and whether it could only be done on initial connect of a channel, but I've just noticed the controls in the Info tab. Once again, thanks for implementing this feature Nino, and thank you for the invaluable work you do with this tool.
