### ISSUE TITLE
Hide (manually) recovered videos

### ISSUE THREAD

**Issue by TheTyrius** [ninsky/recovermyvideotracker#8]
To help me keep track, it would be great to be able to hide deleted videos that I have found a replacement for, so I don't readd it to the playlist multiple times, or spend time researching a video I already recovered a while ago.

**Describe the solution you'd like**
A button to hide an entry (or rather mark it as "solved").

**Comment by ninsky** [comment]
Hello TheTyrius

Yes, that would be a usable feature. I'm thinking about a "move to archive" button. I have put this on my todo list with medium priority.

Thanks for your suggestion and best regards
Nino

**Comment by ninsky** [comment]
Hi TheTyrius

I've rolled out a feature to archive recovered video. I think this should do the trick.

BR
Nino
