### ISSUE TITLE
22 Recovered videos in email 

### ISSUE THREAD

**Issue by stefan5641** [ninsky/recovermyvideotracker#9]
but shows only 5 on the website

**Comment by ninsky** [comment]
Hi Stefan, 

can you tell me the date of the day when you've received the email? 

BR - Nino

**Comment by stefan5641** [comment]
Hi Nino,

Thanks for your reply. I received the mail on the 5th of september.

Kind regards,
Stefan

**Comment by ninsky** [comment]
I had to flush the database on September 5th. I'm pretty sure that this is the reason for your issue. This is fixed. If you encounter any more strange issues, please let me know.

**Comment by stefan5641** [comment]
So the vids are gone?

Regards,
Stefan

**Comment by ninsky** [comment]
Hello Stefan

Yes, I'm sorry to say that the history of your recoverd videos before September 5th is gone.

BR
Nino

**Comment by stefan5641** [comment]
Oh, ok then. Still thanks for helping me figure stuff out.

Best,
Stefan
